config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'awaiting_confirmation', :to => "users#confirmation", :as => 'confirm_user'
  put '/admin/users/:user_id/permissions', :to => 'admin/permissions#update', :as => :update_user_permissions

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end

  root :to => "projects#index"

  resources :files

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tickets, :dependent => :delete_all

  validates :name, :presence => true

  has_many :permissions, :as => :thing

  scope :readable_by, lambda { |user| joins(:permissions).where(:permissions => {:action => "view", :user_id => user.id})}

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authorize_admin!,    :except => [:index, :show]
  before_filter :authenticate_user!,  :only   => [:index, :show]
  before_filter :find_project,        :only   => [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user).all
  end

  def show
    @tickets = @project.tickets
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, :notice => "Project has been deleted."
  end

  private

    def find_project
      @project = Project.for(current_user).find(params[:id])

      rescue ActiveRecord::RecordNotFound
        redirect_to projects_url, :alert => "The project you were looking for could not be found."
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  = f.error_messages
  = f.input :name
  = f.submit

app/views/projects/edit.html.haml
%h2 Edit Project

= render 'projects/form'

app/views/projects/index.html.haml
- admin_only do
  = link_to "New Project", new_project_path

%h2 Projects

%ul#projects
  - for project in @projects
    %li= link_to project.name, project

app/views/projects/new.html.haml
%h2 New Project

= render 'projects/form'

app/views/projects/show.html.haml
- title(@project.name, "Projects")

%h2= @project.name

- admin_only do
  = link_to "Edit Project", edit_project_path(@project)
  = link_to "Delete Project", @project, :method => :delete, :confirm => "Are you sure to delete this project"

- authorized?("create tickets".to_sym, @project) do
  = link_to "New Ticket", new_project_ticket_path(@project)

= form_tag search_project_tickets_path(@project), :method => :get do
  = label_tag "search"
  = text_field_tag "search", params[:search]
  = submit_tag "Search"

%ul
  - @tickets.each do |ticket|
    %li
      = render ticket.state if ticket.state
      = "# #{ticket.id} - "
      = link_to ticket.title, [@project, ticket]